language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: Banque
      script:
        - cd Threads/Banque
        - echo "Testbot at work..."
        - mvn clean test
    - stage: LecteursRedacteurs
      script:
        - cd Threads/LecteursRedacteurs
        - echo "Testbot at work..."
        - mvn clean test
